#!/system/bin/sh
set -e
set -x

export $(grep -v '^#' /blackbox/wtfos/device/$(getprop ro.product.device).env | xargs)
#disable selinux
tries=0
until [ $(getenforce) = "Permissive" ] || [ $tries -eq 25 ]
do
    busybox devmem ${WTFOS_SELINUX_DISABLE} 32 0
    tries=$((tries+1))
done

#remount system so we can patch it
if mount | grep "/dev/loop"; then 
    while  mount | grep "/dev/loop";
    do
        /system/bin/umount -d -l /system
        sleep 1
    done
    echo "wtfos: loopmount unmounted"
fi

while mount | grep '/system ext4 ro' -q > /dev/null;
do 
    /system/bin/mount -o rw,remount /system
    sleep 1
done

#clean any wtfos installation
sed -i '/#wtfos/,/#\/wtfos/d' /system/bin/${WTFOS_TARGET_SCRIPT}
#keep selinux disable and adb unlock
sed -i '/^#!\/system\/bin\/sh$/r /blackbox/wtfos/templates/adb-only-tpl.sh' /system/bin/${WTFOS_TARGET_SCRIPT}
#no blackbox, so replace var
busybox sed -i "s/\${WTFOS_SELINUX_DISABLE}/${WTFOS_SELINUX_DISABLE}/g" /system/bin/${WTFOS_TARGET_SCRIPT}

restorecon /system/bin/${WTFOS_TARGET_SCRIPT}

sync
