#!/system/bin/sh
set -e
set -x

export $(grep -v '^#' /blackbox/wtfos/device/$(getprop ro.product.device).env | xargs)
#disable selinux
busybox devmem ${WTFOS_SELINUX_DISABLE} 32 0

#remount system so we can patch it
if mount | grep "/dev/loop"; then 
    while  mount | grep "/dev/loop";
    do
        /system/bin/umount -d -l /system
        sleep 1
    done
    echo "wtfos: loopmount unmounted"
fi

while mount | grep '/system ext4 ro' -q > /dev/null;
do 
    /system/bin/mount -o rw,remount /system
    sleep 1
done

#clean any previous wtfos installation
sed -i '/#wtfos/,/#\/wtfos/d' /system/bin/${WTFOS_TARGET_SCRIPT}

restorecon /system/bin/${WTFOS_TARGET_SCRIPT}

sync
