#!/system/bin/sh

if  mount | grep -q "/dev/loop"; then
    echo "please uninstall wtfos first with: opkg remove --force-removal-of-dependent-packages wtfos wtfos-system"
    exit 1
fi

remove_adb()
{
    #inactive system
    until mount | grep 'system_2 /system' -q > /dev/null;
    do 
        mount -t ext4 /dev/block/platform/soc/f0000000.ahb/f0400000.dwmmc0/mirror/system_2 /system
        sleep 1
    done

    sed -i '/#wtfos/,/#\/wtfos/d' /system/bin/${WTFOS_TARGET_SCRIPT}
    restorecon /system/bin/${WTFOS_TARGET_SCRIPT}
    sync

    while mount | grep 'system_2 /system' -q > /dev/null;
    do 
        /system/bin/umount -d -l /system
        sleep 1
    done

    #active system
    while mount | grep '/system ext4 ro' -q > /dev/null;
    do 
        /system/bin/mount -o rw,remount /system
        sleep 1
    done
    sed -i '/#wtfos/,/#\/wtfos/d' /system/bin/${WTFOS_TARGET_SCRIPT}
    restorecon /system/bin/${WTFOS_TARGET_SCRIPT}
    sync
}

if [ "$1" = "-q" ]; then
    remove_adb
    exit 0
fi

echo "Are you sure? y/n"
read -n 1 -r
echo ""
if [ "$REPLY" = "y" ]
then
    remove_adb
    echo "done, please reboot"
else 
    echo "didn't answer 'y', not doing anything"
fi
